### ISSUE TITLE
接口高负载时报错

### ISSUE THREAD

**Issue by Nyano1337** [Tongrens/SubmitTool#1]
忘记截图了，大概就是
https://github.com/Tongrens/SubmitTool/blob/d02cbd9435543ff297f53dedfb0bf75cf8814faf/SubmitTool.py#L26

`JSONDecodeError("Expecting value", s, err.value) from None`
`json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by Tongrens** [comment]
```python
try:
    info = json.loads(requests.get(get_info_url).text)  # 获取提交的数据
except json.decoder.JSONDecodeError:
    print('获取数据失败，将再次获取')
    return False
```
