### ISSUE TITLE
请求作者更新下脚本，多谢多谢！！

### ISSUE THREAD

**Issue by 1enco** [Tongrens/SubmitTool#4]
新增一个选择题功能，选择题内容如下：

整数+整数=
a.整数
b.整数
c.整数
d.整数

11+15=
a.24
b.25
c.26
d.27

**Comment by Tongrens** [comment]
小程序端不是本来就有选择的功能嘛

**Comment by Tongrens** [comment]
> 新增一个选择题功能，选择题内容如下：
> 
> 整数+整数= a.整数 b.整数 c.整数 d.整数
> 
> 11+15= a.24 b.25 c.26 d.27

小程序端不是本来就有选择的功能嘛

**Comment by 1enco** [comment]
试过很多次好像都是在选择题上挂掉了的😥



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年04月15日 23:47 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Tongrens/SubmitTool] 请求作者更新下脚本，多谢多谢！！ (Issue #4) |

新增一个选择题功能，选择题内容如下：

整数+整数= a.整数 b.整数 c.整数 d.整数

11+15= a.24 b.25 c.26 d.27

小程序端不是本来就有选择的功能嘛

**Comment by Tongrens** [comment]
![微信截图_20240416030001](https://github.com/Tongrens/SubmitTool/assets/73508047/9d05edbb-5bcb-4cb4-94d0-95c852dc6c2c)
![微信截图_20240416030054](https://github.com/Tongrens/SubmitTool/assets/73508047/47665db7-c6b0-49c6-8d9e-ba62c1e568b9)
这不是没问题吗

**Comment by Tongrens** [comment]
> 试过很多次好像都是在选择题上挂掉了的😥
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2024年04月15日 23:47 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [Tongrens/SubmitTool] 请求作者更新下脚本，多谢多谢！！ (Issue #4) | 新增一个选择题功能，选择题内容如下： 整数+整数= a.整数 b.整数 c.整数 d.整数 11+15= a.24 b.25 c.26 d.27 小程序端不是本来就有选择的功能嘛 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

![微信截图_20240416030001](https://github.com/Tongrens/SubmitTool/assets/73508047/b3a3404c-f186-40d6-8207-7852acb5f0d7)
![微信截图_20240416030054](https://github.com/Tongrens/SubmitTool/assets/73508047/dd90224b-c413-416d-b611-da81214433bc)
这不是没问题吗

**Comment by 1enco** [comment]
![微信截图_20240416092931](https://github.com/Tongrens/SubmitTool/assets/139854462/cf17b20f-947b-4e1a-975a-66d040ddc242)
那是不是要先把所有可能出现的加法先保存在信息栏里呀，工作量可能有点大喔。

**Comment by 1enco** [comment]
![微信截图_20240416092931](https://github.com/Tongrens/SubmitTool/assets/139854462/1a85e576-b9ec-482c-9192-1a54dd829434)
试了下只有手动填写比较合适

**Comment by Tongrens** [comment]
脚本没有自动搜题答题功能，仅适用于报名工具内个人信息的自动填写。
